export const PostItem=[
    {
        dp:"https://images.pexels.com/photos/3211476/pexels-photo-3211476.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"babumoshay",
        name:"Will Smith",
        post:"https://images.pexels.com/photos/14769376/pexels-photo-14769376.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        likes:50,
        profile:"/babumoshay",
        noti:"Liked your post",
        chat:"/chat1",
        story:"/story1",
        online:true
    },
    {
        dp:"https://images.pexels.com/photos/804009/pexels-photo-804009.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"noobmaster69",
        name:"Bella Boy",
        post:"https://images.pexels.com/photos/571169/pexels-photo-571169.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        likes:68,
        story:"/story2",
        profile:"/noobmaster69"
    },
    {
        dp:"https://images.pexels.com/photos/1988686/pexels-photo-1988686.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"torukmakhto",
        name:"Dash Runner",
        post:"https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:502,
        story:"/story3",
        profile:"/torukmakhto"
    },
    {
        dp:"https://images.pexels.com/photos/14529648/pexels-photo-14529648.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        username:"dentismentis",
        name:"Jack Sparrow",
        post:"https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:562,
        story:"/story4",
        profile:"/dentismentis",
    },
    {
        dp:"https://images.pexels.com/photos/801861/pexels-photo-801861.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"wakandaforever",
        name:"Black Billy",
        post:"https://images.pexels.com/photos/6142739/pexels-photo-6142739.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:860,
        story:"/story5",
        profile:"/wakandaforever"
    },
    {
        dp:"https://images.pexels.com/photos/14529648/pexels-photo-14529648.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        username:"chachachoudryy",
        name:"Cat Smith",
        post:"https://images.pexels.com/photos/4340670/pexels-photo-4340670.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:290,
        profile:"/chachachoudryy",
        online:true,
        noti:"Liked your post",
        story:"/story6",
        chat:"/chat2",
    },
    {
        dp:"https://images.pexels.com/photos/2805050/pexels-photo-2805050.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"aisehikuchbhi",
        name:"Elon Mast",
        post:"https://images.pexels.com/photos/2040627/pexels-photo-2040627.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:789,
        story:"/story6",
        profile:"/aisehikuchbhi"
    },
    {
        dp:"https://images.pexels.com/photos/1812634/pexels-photo-1812634.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"meranammukesh",
        name:"Mukesh Mukesh",
        post:"https://images.pexels.com/photos/1020016/pexels-photo-1020016.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:198,
        story:"/story7",
        profile:"/meranammukesh"
    },
    {
        dp:"https://images.pexels.com/photos/1054048/pexels-photo-1054048.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"notwonderwomen",
        name:"Ordenary Women",
        // post:"https://images.pexels.com/photos/71104/utah-mountain-biking-bike-biking-71104.jpeg?auto=compress&cs=tinysrgb&w=1600",
        tweet:"Hey there im not usign whatsapp erytuyihjvtrghu  tvrrwrt vrt vtr vr tv e  wvwd cwrcjrvv4rv4  v4 ccor r2  ",
        likes:657,
        profile:"/notwonderwomen",
        online:true,
        noti:"Commented on your post",
        story:"/story8",
        chat:"/chat3",
    },
    {
        dp:"https://images.pexels.com/photos/1054048/pexels-photo-1054048.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"lazzydazzy",
        name:"Dasy doe",
        post:"https://images.pexels.com/photos/1553958/pexels-photo-1553958.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:897,
        story:"/story9",
        profile:"/desidazzy"
    },
    {
        dp:"https://images.pexels.com/photos/7790836/pexels-photo-7790836.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"pancake",
        name:"Cane wong",
        post:"https://images.pexels.com/photos/1756086/pexels-photo-1756086.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:543,
        profile:"/pancake",
        online:true,
        story:"/story10",
        noti:"Liked your post",
        chat:"/chat4",
    },
    {
        dp:"https://images.pexels.com/photos/2748242/pexels-photo-2748242.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"candyicecream",
        name:"Vanila Flavour",
        post:"https://images.pexels.com/photos/1056497/pexels-photo-1056497.jpeg?auto=compress&cs=tinysrgb&w=1600",
        likes:867,
        story:"/story11",
        profile:"/candyicecream"
    },
    {
        dp:"https://images.pexels.com/photos/2388213/pexels-photo-2388213.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username:"ghadisabun",
        name:"Istemal Vishwas",
        post:"https://images.pexels.com/photos/164222/pexels-photo-164222.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        likes:457,
        profile:"/ghadisabun",
        online:true,
        noti:"Commented your post",
        story:"/story12",
        chat:"/chat5",
    },
    
]

